language: python

# cache pip dependency
cache: pip

sudo: required

jobs:
    include:
        - python: "2.7"
          install:
              - pip install -r requirements.txt
          script:
              - sudo env "PATH=$PATH" python --version          # environment check
              - sudo env "PATH=$PATH" python -c 'import psutil' # ensure deps are installed.

              # Some tests do not pass on travis-ci.
              # E.g.: redis, mysql, zookeeper, etcd needs a docker to test.
              # Disable them temporarily.
              # -- by xp 2020 Jan 27

              # Enable debug log: UT_DEBUG=1
              - >-
                  sudo env "PATH=$PATH" ./script/run-test
                  argchecker
                  aws
                  awssign
                  cacheable
                  cachepool
                  cgrouparch
                  csvutil
                  daemonize
                  dictutil
                  ectypes
                  fsutil
                  heap
                  httpmultipart
                  humannum
                  jobq
                  jobscheduler
                  logcollector
                  logutil
                  mathtoy
                  mime
                  modutil
                  net
                  p3json
                  portlock
                  priorityqueue
                  proc
                  profiling
                  rangeset
                  ratelimiter
                  request
                  shell
                  strutil
                  threadutil
                  timeutil
                  utfjson
                  utfyaml
                  wsjobd

# after_success:
#   - pip install python-coveralls && coveralls
